//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public short ID { get; set; }
        public Nullable<short> ShopID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
